package it.italiaonline.rnd

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author gsus
 * @date 15-12-2016 12.55
 */
@Slf4j
class CompactLapse {
	/**
	 * This method returns always true.
	 */
	Boolean someCompactLapseMethod() {
		true
	}
}
