package it.italiaonline.rnd

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author gsus
 * @date 15-12-2016 12.55
 */
class CompactLapseSpec extends Specification {
	def "someCompactLapseMethod returns true"() {
		setup:
			CompactLapse lib = new CompactLapse()
		when:
			Boolean result = lib.someCompactLapseMethod()
		then:
			result == true
	}
}
